# Generated by Django 6.0 on 2025-12-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="rating",
        ),
    ]
