# Generated by Django 6.0 on 2025-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_recipe_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.FloatField(
                choices=[
                    (1.0, "1"),
                    (1.5, "1.5"),
                    (2.0, "2"),
                    (2.5, "2.5"),
                    (3.0, "3"),
                    (3.5, "3.5"),
                    (4.0, "4"),
                    (4.5, "4.5"),
                    (5.0, "5"),
                    (5.5, "5.5"),
                    (6.0, "6"),
                    (6.5, "6.5"),
                    (7.0, "7"),
                    (7.5, "7.5"),
                    (8.0, "8"),
                    (8.5, "8.5"),
                    (9.0, "9"),
                    (9.5, "9.5"),
                    (10.0, "10"),
                ]
            ),
        ),
    ]
