# Generated by Django 6.0 on 2025-12-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_saverecipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saverecipe",
            options={
                "verbose_name": "Receta guardada",
                "verbose_name_plural": "Recetas guardadas",
            },
        ),
    ]
