# Generated by Django 6.0 on 2025-12-21 09:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_saverecipe_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Dificultad")),
            ],
            options={
                "verbose_name": "Dificultad",
                "verbose_name_plural": "Dificultades",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ManyToManyField(
                to="recipes.difficulty", verbose_name="Dificultad"
            ),
        ),
    ]
