# Generated by Django 6.0 on 2026-01-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_difficulty_recipe_time_recipe_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="food_category",
            field=models.ManyToManyField(
                blank=True, to="recipes.category", verbose_name="Tipo de comida"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.difficulty",
                verbose_name="Dificultad",
            ),
        ),
    ]
