# Generated by Django 6.0 on 2026-01-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0009_remove_recipe_difficulty_alter_recipe_food_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="recipes.difficulty",
                verbose_name="Dificultad",
            ),
            preserve_default=False,
        ),
    ]
