# Generated by Django 6.0 on 2026-01-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="food_category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ManyToManyField(
                to="recipes.difficulty", verbose_name="Dificultad"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="food_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.category",
                verbose_name="Tipo de comida",
            ),
            preserve_default=False,
        ),
    ]
