# Generated by Django 6.0 on 2026-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0011_remove_recipe_difficulty_remove_recipe_food_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="food_category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="food_category",
            field=models.ManyToManyField(
                to="recipes.category", verbose_name="Tipo de comida"
            ),
        ),
    ]
