# Generated by Django 6.0 on 2026-01-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_remove_recipe_food_category_recipe_food_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.difficulty",
                verbose_name="Dificultad",
            ),
            preserve_default=False,
        ),
    ]
