# Generated by Django 6.0 on 2026-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "g"),
                    ("kg", "kg"),
                    ("ml", "ml"),
                    ("L", "L"),
                    ("u", "uds"),
                    ("cda", "cda"),
                    ("cdta", "cdta"),
                ],
                max_length=10,
                null=True,
                verbose_name="Unidad",
            ),
        ),
    ]
