# Generated by Django 6.0 on 2026-01-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.recipe",
                verbose_name="Receta",
            ),
        ),
    ]
