# Generated by Django 6.0 on 2026-02-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_alter_ingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.FloatField(
                choices=[
                    (0.5, "0.5"),
                    (1.0, "1"),
                    (1.5, "1.5"),
                    (2.0, "2"),
                    (2.5, "2.5"),
                    (3.0, "3"),
                    (3.5, "3.5"),
                    (4.0, "4"),
                    (4.5, "4.5"),
                    (5.0, "5"),
                    (5.5, "5.5"),
                    (6.0, "6"),
                    (6.5, "6.5"),
                    (7.0, "7"),
                    (7.5, "7.5"),
                    (8.0, "8"),
                    (8.5, "8.5"),
                    (9.0, "9"),
                    (9.5, "9.5"),
                    (10.0, "10"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=1, upload_to="recipes/images/", verbose_name="Foto de la receta"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="steps",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
