# Generated by Django 6.0 on 2026-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_alter_rating_value_alter_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("al gusto", "-"),
                    ("g", "g"),
                    ("kg", "kg"),
                    ("ml", "ml"),
                    ("L", "L"),
                    ("", "uds"),
                    ("cda", "cda"),
                    ("cdta", "cdta"),
                ],
                default="al gusto",
                max_length=10,
                verbose_name="Unidad",
            ),
        ),
    ]
