# Generated by Django 6.0 on 2026-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("none", "-"),
                    ("g", "g"),
                    ("kg", "kg"),
                    ("ml", "ml"),
                    ("L", "L"),
                    ("", "uds"),
                    ("cda", "cda"),
                    ("cdta", "cdta"),
                ],
                default="none",
                max_length=10,
                verbose_name="Unidad",
            ),
        ),
    ]
