# Generated by Django 6.0 on 2026-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0023_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Tipo de comida"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_es",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Tipo de comida"
            ),
        ),
        migrations.AddField(
            model_name="difficulty",
            name="name_en",
            field=models.CharField(max_length=10, null=True, verbose_name="Dificultad"),
        ),
        migrations.AddField(
            model_name="difficulty",
            name="name_es",
            field=models.CharField(max_length=10, null=True, verbose_name="Dificultad"),
        ),
    ]
